apiVersion: v1
kind: Endpoints
metadata:
  name: harbor
  namespace: jenkins
subsets:
- addresses:
  - ip: 192.168.101.13
  ports:
  - port: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: harbor
  namespace: jenkins
spec:
  ports:
  - port: 8090
    targetPort: 8090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: harbor-web
  namespace: jenkins
spec:
  rules:
    - host: harbor.devops.cn
      http:
        paths:
        - backend:
            serviceName: harbor
            servicePort: 8090
          path: /

