defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/root/django/yaml/8.ingress/ssl/ssl.crt"
      keyFile = "/root/django/yaml/8.ingress/ssl/ssl.key"
