apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    type: mysqlpv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/mysql/"
    server: 192.168.101.10
    readOnly: false
