apiVersion: v1
kind: PersistentVolume
metadata:
  name: django
  labels:
    type: djangopv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/django/"
    server: 192.168.101.10
    readOnly: false
