apiVersion: v1
kind: ReplicationController
metadata:
  name: myblog
spec:
  replicas: 1
  selector:
    app: myblog
  template:
    metadata:
      labels:
        app: myblog
    spec:
      containers:
        - name: myblog
          image: 192.168.101.10:5000/myblog:v1
          ports:
          - containerPort: 8002
          env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: myblog
                key: MYSQL_HOST
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: myblog
                key: MYSQL_USER
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: myblog
                key: MYSQL_PORT
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myblog
                key: MYSQL_PASSWD
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 100m
          readinessProbe:
            httpGet:
              path: /blog/index/
              port: 8002
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /blog/index/
              port: 8002
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 15
